galaxy_info:
  author: sinansh
  description: Installs and configures Sysmon for Linux.
  company: sinansh
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - security
    - sysmon
    - logging
    - edr

dependencies: []
