galaxy_info:
  author: sinansh
  description: Configures Rsyslog to forward events to a SIEM.
  company: sinansh
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - security
    - rsyslog
    - siem
    - logging

dependencies: []
